version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    deploy:
      mode: replicated
      replicas: 1

volumes:
  data: {}
  letsencrypt: {}